#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_30
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_29
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_27
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_26
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_28

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_31
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_7
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_8
#define AUDIO_CODEC_ES8388_ADDR  ES8388_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_3
#define BOOT_BUTTON_GPIO        GPIO_NUM_35

// TL043WVV02-B1900A — see DFRobot BOARD_DFROBOT_FIREBEETLE_ESP32_P4_LCD_4_3.h
#define DISPLAY_WIDTH           480
#define DISPLAY_HEIGHT          800

#define PIN_NUM_LCD_RST         GPIO_NUM_21
#define LCD_RST_ACTIVE_HIGH     false

#define LCD_BIT_PER_PIXEL       16
#define LCD_MIPI_DSI_LANE_NUM   2
#define LCD_MIPI_DSI_LANE_BITRATE_MBPS 1000
#define LCD_MIPI_DPI_CLK_MHZ    28

#define MIPI_DSI_PHY_PWR_LDO_CHAN       3
#define MIPI_DSI_PHY_PWR_LDO_VOLTAGE_MV 2500

#define DISPLAY_SWAP_XY         false
#define DISPLAY_MIRROR_X        false
#define DISPLAY_MIRROR_Y        false
#define DISPLAY_OFFSET_X        0
#define DISPLAY_OFFSET_Y        0

#define DISPLAY_BACKLIGHT_PIN              GPIO_NUM_11
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT    false

#endif // _BOARD_CONFIG_H_
